### ISSUE TITLE
Does autoload inits Fastify or where is it defined?

### ISSUE THREAD

**Issue by whoisjuan** [mattwaler/fastify-starter#1]
Hey! First of all, thanks for creating this starter. It has been a great example to get going with fastify.

There's, however, one thing about your project that confuses me. I was trying to set up a server option, and I noticed that your project doesn't require `fastify` anywhere.  In the `fastify-autoload` examples I have seen around `fastify` is initialized before the autoload module. e.g.: https://github.com/fastify/fastify-autoload#example 

So how does this work exactly? Where exactly is fastify defined in the context of this project, and how can I set up options such as:

```
const fastify = require('fastify')({
  ignoreTrailingSlash: true
})
```

I feel like I'm missing something obvious but can't figure it out.

**Comment by whoisjuan** [comment]
Nevermind. I'm an idiot. I now see that is `fastify-cli` the one that is mocking the server file where fastify is defined. I'm still not sure how to set options through this mechanism, though. The fastify CLI suggests defining them in a way that doesn't seem to work for me: https://github.com/fastify/fastify-cli

Do you have a particular way to set server configurations?

**Comment by mattwaler** [comment]
Yeah, you got it @whoisjuan!

My recommendation to set certain server configurations is to just add them to your `.env` file, following the CLI's docs variable names and they will be added automatically!

https://github.com/fastify/fastify-cli#options

For example, to enable pretty logging, you can just add this to your `.env` file:

```env
FASTIFY_PRETTY_LOGS=true
```
