### ISSUE TITLE
GCP Deploy

### ISSUE THREAD

**Issue by johntom** [mattwaler/fastify-starter#2]
Hi,
I'm testing your repo as a port of a an aurliea js frontend calling a fastify bakend. Both projects are deployed on GCP. About half way thru thje port I decided to test to deploy to gcp and if fails. Any ideas on how to deploy your repo to GCP?
Thanks for your great contribution,
John

**Comment by mattwaler** [comment]
Hey @johntom,

I would consult the fastify docs and repo directly for instructions on how to deploy to GCP! I've never done it so I wouldn't be of much help sorry!
